# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 513)
        
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(320, 210, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("\n"
"color: rgb(255, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 301, 521))
        self.label_2.setStyleSheet("background-image: url(:/icone/login_side.png);\n"
"border-top-left-radius:50;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(300, -10, 331, 521))
        self.label_3.setStyleSheet("border-bottom-right-radius:50;\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_26 = QtWidgets.QPushButton(Form)
        self.pushButton_26.setGeometry(QtCore.QRect(495, 370, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"background-color: rgb(165, 120, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"background-color: rgb(170, 170, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icone/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon)
        self.pushButton_26.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(320, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(355, 240, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("\n"
"color: rgb(255, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(450, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setStyleSheet("border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 10px;")
        self.lineEdit_22.setCursorPosition(0)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(320, 370, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_24.setObjectName("label_24")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(450, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setStyleSheet("border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 10px;")
        self.lineEdit_23.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_23.setCursorPosition(0)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(330, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pushButton_27 = QtWidgets.QPushButton(Form)
        self.pushButton_27.setGeometry(QtCore.QRect(330, 290, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"background-color: rgb(112, 255, 133);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: beige;\n"
"min-width: 10em;\n"
"padding: 6px;\n"
"\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"\n"
"    \n"
"    background-color: rgb(55, 217, 109);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icone/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_27.setIcon(icon1)
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(420, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_26.setText(_translate("Form", "Réinitialiser "))
        self.label_22.setText(_translate("Form", "Nom Utilisateur   "))
        self.label_26.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.lineEdit_22.setPlaceholderText(_translate("Form", "Utilisateur"))
        self.label_24.setText(_translate("Form", "Mot de pass oublié ? "))
        self.lineEdit_23.setPlaceholderText(_translate("Form", "Mot de pass"))
        self.label_23.setText(_translate("Form", "Mot de pass "))
        self.pushButton_27.setText(_translate("Form", "Login"))
        self.label_27.setText(_translate("Form", "LOGIN"))
import iconne_rc

    
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())    