# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'des_v1.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QListView,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTableWidget, QTableWidgetItem,
    QTextEdit, QWidget)
import iconne_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1324, 665)
        font = QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(260, 30, 1041, 591))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(13)
        self.tabWidget.setFont(font1)
        self.tab_17 = QWidget()
        self.tab_17.setObjectName(u"tab_17")
        self.label_22 = QLabel(self.tab_17)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(160, 170, 141, 31))
        font2 = QFont()
        font2.setPointSize(13)
        self.label_22.setFont(font2)
        self.label_23 = QLabel(self.tab_17)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(160, 230, 101, 31))
        self.label_23.setFont(font2)
        self.lineEdit_22 = QLineEdit(self.tab_17)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(330, 170, 211, 31))
        self.lineEdit_22.setFont(font2)
        self.lineEdit_22.setCursorPosition(0)
        self.lineEdit_23 = QLineEdit(self.tab_17)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(330, 230, 211, 31))
        self.lineEdit_23.setFont(font2)
        self.lineEdit_23.setCursorPosition(0)
        self.label_24 = QLabel(self.tab_17)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(180, 340, 161, 31))
        self.label_24.setFont(font2)
        self.label_24.setStyleSheet(u"color: rgb(0, 170, 255);")
        self.pushButton_26 = QPushButton(self.tab_17)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(420, 340, 131, 31))
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u":/icone/reset.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_26.setIcon(icon)
        self.pushButton_26.setIconSize(QSize(22, 22))
        self.pushButton_27 = QPushButton(self.tab_17)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(160, 280, 391, 41))
        self.pushButton_27.setFont(font2)
        self.pushButton_27.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon1 = QIcon()
        icon1.addFile(u":/icone/login.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_27.setIcon(icon1)
        self.tabWidget.addTab(self.tab_17, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.lineEdit = QLineEdit(self.tab)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(690, 50, 301, 31))
        self.lineEdit.setFont(font2)
        self.comboBox = QComboBox(self.tab)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(278, 51, 201, 31))
        self.comboBox.setFont(font2)
        self.comboBox.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 50, 61, 20))
        self.label.setFont(font2)
        self.pushButton_7 = QPushButton(self.tab)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(14, 42, 111, 41))
        self.pushButton_7.setFont(font2)
        self.pushButton_7.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon2 = QIcon()
        icon2.addFile(u":/icone/add.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.tableWidget = QTableWidget(self.tab)
        if (self.tableWidget.columnCount() < 4):
            self.tableWidget.setColumnCount(4)
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem.setFont(font3);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        font4 = QFont()
        font4.setPointSize(11)
        font4.setBold(False)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem1.setFont(font4);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem2.setFont(font4);
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem3.setFont(font4);
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QRect(10, 110, 981, 351))
        self.tableWidget.setMaximumSize(QSize(16777215, 16777215))
        self.tableWidget.setFont(font2)
        self.listView = QListView(self.tab)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(10, 470, 481, 71))
        font5 = QFont()
        font5.setFamilies([u"MS Shell Dlg 2"])
        font5.setPointSize(14)
        font5.setBold(False)
        font5.setItalic(False)
        self.listView.setFont(font5)
        self.listView.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_13 = QPushButton(self.tab)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(550, 470, 211, 71))
        self.pushButton_13.setFont(font2)
        self.pushButton_13.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon3 = QIcon()
        icon3.addFile(u":/icone/land-sell-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_13.setIcon(icon3)
        self.pushButton_13.setIconSize(QSize(26, 26))
        self.pushButton_14 = QPushButton(self.tab)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(790, 470, 201, 71))
        self.pushButton_14.setFont(font2)
        self.pushButton_14.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        icon4 = QIcon()
        icon4.addFile(u":/icone/annuler.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_14.setIcon(icon4)
        self.pushButton_14.setIconSize(QSize(22, 22))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 10, 1021, 521))
        self.tabWidget_2.setFont(font2)
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.lineEdit_2 = QLineEdit(self.tab_8)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(580, 20, 211, 31))
        self.lineEdit_2.setFont(font2)
        self.comboBox_2 = QComboBox(self.tab_8)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(330, 20, 201, 31))
        self.comboBox_2.setFont(font2)
        self.comboBox_2.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.label_2 = QLabel(self.tab_8)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(230, 20, 91, 20))
        self.label_2.setFont(font2)
        self.pushButton_8 = QPushButton(self.tab_8)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(30, 20, 121, 31))
        self.pushButton_8.setFont(font2)
        self.pushButton_8.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon5 = QIcon()
        icon5.addFile(u":/icone/searche.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_8.setIcon(icon5)
        self.tableWidget_2 = QTableWidget(self.tab_8)
        if (self.tableWidget_2.columnCount() < 4):
            self.tableWidget_2.setColumnCount(4)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, __qtablewidgetitem7)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setGeometry(QRect(25, 70, 941, 381))
        self.tableWidget_2.setFont(font2)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.pushButton_9 = QPushButton(self.tab_9)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(300, 430, 201, 41))
        self.pushButton_9.setFont(font2)
        self.pushButton_9.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        self.pushButton_9.setIcon(icon2)
        self.comboBox_3 = QComboBox(self.tab_9)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(558, 80, 211, 41))
        self.comboBox_3.setFont(font2)
        self.comboBox_3.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.label_3 = QLabel(self.tab_9)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(430, 90, 71, 20))
        self.label_3.setFont(font2)
        self.lineEdit_3 = QLineEdit(self.tab_9)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(560, 160, 211, 31))
        self.lineEdit_3.setFont(font2)
        self.label_4 = QLabel(self.tab_9)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(468, 160, 61, 20))
        self.label_4.setFont(font2)
        self.lineEdit_4 = QLineEdit(self.tab_9)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(114, 90, 211, 31))
        self.lineEdit_4.setFont(font2)
        self.lineEdit_4.setCursorPosition(0)
        self.label_5 = QLabel(self.tab_9)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(44, 100, 47, 13))
        self.label_5.setFont(font2)
        self.lineEdit_5 = QLineEdit(self.tab_9)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(114, 150, 211, 161))
        self.lineEdit_5.setFont(font2)
        self.label_6 = QLabel(self.tab_9)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 160, 71, 21))
        self.label_6.setFont(font2)
        self.lineEdit_6 = QLineEdit(self.tab_9)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(560, 220, 211, 31))
        self.lineEdit_6.setFont(font2)
        self.label_7 = QLabel(self.tab_9)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(450, 220, 61, 20))
        self.label_7.setFont(font2)
        self.label_8 = QLabel(self.tab_9)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(468, 280, 61, 20))
        self.label_8.setFont(font2)
        self.lineEdit_7 = QLineEdit(self.tab_9)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(560, 280, 211, 31))
        self.lineEdit_7.setFont(font2)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.label_9 = QLabel(self.tab_10)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 180, 61, 16))
        self.label_9.setFont(font2)
        self.label_10 = QLabel(self.tab_10)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(450, 280, 71, 20))
        self.label_10.setFont(font2)
        self.lineEdit_8 = QLineEdit(self.tab_10)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(560, 260, 211, 31))
        self.lineEdit_8.setFont(font2)
        self.label_11 = QLabel(self.tab_10)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 120, 47, 13))
        self.label_11.setFont(font2)
        self.lineEdit_9 = QLineEdit(self.tab_10)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(552, 130, 211, 31))
        self.lineEdit_9.setFont(font2)
        self.pushButton_10 = QPushButton(self.tab_10)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(110, 420, 201, 41))
        self.pushButton_10.setFont(font2)
        self.pushButton_10.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        icon6 = QIcon()
        icon6.addFile(u":/icone/delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QSize(22, 22))
        self.lineEdit_10 = QLineEdit(self.tab_10)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(222, 30, 211, 31))
        self.lineEdit_10.setFont(font2)
        self.lineEdit_11 = QLineEdit(self.tab_10)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(110, 110, 211, 31))
        self.lineEdit_11.setFont(font2)
        self.lineEdit_12 = QLineEdit(self.tab_10)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(110, 170, 211, 161))
        self.lineEdit_12.setFont(font2)
        self.label_12 = QLabel(self.tab_10)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(420, 130, 91, 20))
        self.label_12.setFont(font2)
        self.label_13 = QLabel(self.tab_10)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(150, 30, 61, 20))
        self.label_13.setFont(font2)
        self.pushButton_11 = QPushButton(self.tab_10)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(510, 420, 201, 41))
        self.pushButton_11.setFont(font2)
        self.pushButton_11.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon7 = QIcon()
        icon7.addFile(u":/icone/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setIconSize(QSize(22, 22))
        self.pushButton_12 = QPushButton(self.tab_10)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(470, 30, 221, 31))
        self.pushButton_12.setFont(font2)
        self.pushButton_12.setStyleSheet(u"background-color: rgb(19, 173, 255);\n"
"")
        self.pushButton_12.setIcon(icon5)
        self.label_25 = QLabel(self.tab_10)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(410, 200, 101, 20))
        self.label_25.setFont(font2)
        self.lineEdit_24 = QLineEdit(self.tab_10)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(552, 200, 211, 31))
        self.lineEdit_24.setFont(font2)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget_3 = QTabWidget(self.tab_3)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 10, 1021, 521))
        self.tabWidget_3.setFont(font2)
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.lineEdit_13 = QLineEdit(self.tab_13)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(190, 10, 311, 41))
        self.lineEdit_13.setFont(font2)
        self.pushButton_15 = QPushButton(self.tab_13)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(30, 10, 151, 41))
        self.pushButton_15.setFont(font2)
        self.pushButton_15.setStyleSheet(u"background-color: rgb(19, 173, 255);\n"
"")
        self.pushButton_15.setIcon(icon5)
        self.tableWidget_3 = QTableWidget(self.tab_13)
        if (self.tableWidget_3.columnCount() < 4):
            self.tableWidget_3.setColumnCount(4)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        self.tableWidget_3.setObjectName(u"tableWidget_3")
        self.tableWidget_3.setGeometry(QRect(25, 70, 701, 381))
        self.tableWidget_3.setFont(font2)
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.pushButton_16 = QPushButton(self.tab_14)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(470, 420, 201, 41))
        self.pushButton_16.setFont(font2)
        self.pushButton_16.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        self.pushButton_16.setIcon(icon7)
        self.pushButton_16.setIconSize(QSize(22, 22))
        self.lineEdit_14 = QLineEdit(self.tab_14)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(280, 160, 211, 31))
        self.lineEdit_14.setFont(font2)
        self.label_16 = QLabel(self.tab_14)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(188, 160, 61, 20))
        self.label_16.setFont(font2)
        self.lineEdit_15 = QLineEdit(self.tab_14)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(280, 100, 211, 31))
        self.lineEdit_15.setFont(font2)
        self.lineEdit_15.setCursorPosition(0)
        self.label_17 = QLabel(self.tab_14)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(190, 110, 47, 13))
        self.label_17.setFont(font2)
        self.lineEdit_17 = QLineEdit(self.tab_14)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(280, 220, 211, 31))
        self.lineEdit_17.setFont(font2)
        self.label_19 = QLabel(self.tab_14)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(190, 220, 51, 20))
        self.label_19.setFont(font2)
        self.label_20 = QLabel(self.tab_14)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(138, 280, 111, 20))
        self.label_20.setFont(font2)
        self.lineEdit_18 = QLineEdit(self.tab_14)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(280, 280, 211, 31))
        self.lineEdit_18.setFont(font2)
        self.lineEdit_18.setDragEnabled(False)
        self.lineEdit_18.setReadOnly(False)
        self.comboBox_4 = QComboBox(self.tab_14)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(530, 30, 211, 41))
        self.comboBox_4.setFont(font2)
        self.comboBox_4.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.lineEdit_16 = QLineEdit(self.tab_14)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(280, 40, 211, 31))
        self.lineEdit_16.setFont(font2)
        self.lineEdit_16.setCursorPosition(0)
        self.pushButton_17 = QPushButton(self.tab_14)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(80, 30, 171, 41))
        self.pushButton_17.setFont(font2)
        self.pushButton_17.setStyleSheet(u"background-color: rgb(19, 173, 255);\n"
"")
        self.pushButton_17.setIcon(icon5)
        self.pushButton_18 = QPushButton(self.tab_14)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(90, 420, 201, 41))
        self.pushButton_18.setFont(font2)
        self.pushButton_18.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.pushButton_18.setIcon(icon6)
        self.pushButton_18.setIconSize(QSize(22, 22))
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox = QGroupBox(self.tab_4)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 50, 1011, 111))
        self.groupBox.setFont(font2)
        self.pushButton_20 = QPushButton(self.groupBox)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(10, 40, 191, 41))
        self.pushButton_20.setFont(font2)
        self.pushButton_20.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        self.pushButton_20.setIcon(icon2)
        self.comboBox_5 = QComboBox(self.groupBox)
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(600, 40, 211, 41))
        self.comboBox_5.setFont(font2)
        self.comboBox_5.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.lineEdit_19 = QLineEdit(self.groupBox)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(230, 40, 211, 41))
        self.lineEdit_19.setFont(font2)
        self.lineEdit_19.setCursorPosition(0)
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(470, 50, 121, 20))
        self.label_18.setFont(font2)
        self.groupBox_2 = QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 220, 1011, 111))
        self.groupBox_2.setFont(font2)
        self.pushButton_21 = QPushButton(self.groupBox_2)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(10, 40, 191, 41))
        self.pushButton_21.setFont(font2)
        self.pushButton_21.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon8 = QIcon()
        icon8.addFile(u":/icone/barre.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_21.setIcon(icon8)
        self.lineEdit_20 = QLineEdit(self.groupBox_2)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(230, 40, 341, 41))
        self.lineEdit_20.setFont(font2)
        self.lineEdit_20.setCursorPosition(0)
        self.pushButton_22 = QPushButton(self.groupBox_2)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(610, 40, 191, 41))
        self.pushButton_22.setFont(font2)
        self.pushButton_22.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon9 = QIcon()
        icon9.addFile(u":/icone/imprimer.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_22.setIcon(icon9)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_4 = QTabWidget(self.tab_5)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(0, 10, 1021, 541))
        self.tabWidget_4.setFont(font2)
        self.tab_15 = QWidget()
        self.tab_15.setObjectName(u"tab_15")
        self.tableWidget_5 = QTableWidget(self.tab_15)
        if (self.tableWidget_5.columnCount() < 4):
            self.tableWidget_5.setColumnCount(4)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, __qtablewidgetitem15)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        self.tableWidget_5.setGeometry(QRect(25, 70, 981, 381))
        self.tableWidget_5.setFont(font2)
        self.dateEdit = QDateEdit(self.tab_15)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(70, 20, 121, 31))
        self.dateEdit.setFont(font2)
        self.dateEdit_2 = QDateEdit(self.tab_15)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setGeometry(QRect(300, 20, 121, 31))
        self.dateEdit_2.setFont(font2)
        self.label_21 = QLabel(self.tab_15)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 30, 21, 16))
        self.label_21.setFont(font2)
        self.label_28 = QLabel(self.tab_15)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(230, 20, 61, 31))
        self.label_28.setFont(font2)
        self.pushButton_24 = QPushButton(self.tab_15)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(680, 30, 201, 31))
        self.pushButton_24.setFont(font2)
        self.pushButton_24.setStyleSheet(u"background-color: rgb(19, 173, 255);\n"
"")
        self.pushButton_24.setIcon(icon5)
        self.textEdit = QTextEdit(self.tab_15)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(900, 30, 101, 31))
        self.textEdit.setFont(font2)
        self.pushButton_31 = QPushButton(self.tab_15)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(840, 460, 161, 41))
        self.pushButton_31.setFont(font2)
        self.pushButton_31.setStyleSheet(u"background-color: rgb(112, 255, 133);\n"
"")
        self.pushButton_31.setIcon(icon9)
        self.pushButton_31.setIconSize(QSize(22, 22))
        self.tabWidget_4.addTab(self.tab_15, "")
        self.tab_16 = QWidget()
        self.tab_16.setObjectName(u"tab_16")
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tableWidget_4 = QTableWidget(self.tab_7)
        if (self.tableWidget_4.columnCount() < 4):
            self.tableWidget_4.setColumnCount(4)
        __qtablewidgetitem16 = QTableWidgetItem()
        __qtablewidgetitem16.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem16.setFont(font3);
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        __qtablewidgetitem17.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem17.setFont(font4);
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        __qtablewidgetitem18.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem18.setFont(font4);
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        __qtablewidgetitem19.setTextAlignment(Qt.AlignCenter);
        __qtablewidgetitem19.setFont(font4);
        self.tableWidget_4.setHorizontalHeaderItem(3, __qtablewidgetitem19)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setEnabled(True)
        self.tableWidget_4.setGeometry(QRect(10, 130, 1011, 351))
        self.tableWidget_4.setMaximumSize(QSize(16777215, 16777215))
        self.tableWidget_4.setFont(font1)
        self.lineEdit_21 = QLineEdit(self.tab_7)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(10, 40, 181, 31))
        self.lineEdit_21.setFont(font1)
        self.comboBox_6 = QComboBox(self.tab_7)
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(450, 40, 151, 31))
        font6 = QFont()
        font6.setFamilies([u"Segoe UI"])
        self.comboBox_6.setFont(font6)
        self.comboBox_6.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.label_14 = QLabel(self.tab_7)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(350, 40, 51, 20))
        self.label_14.setFont(font1)
        self.pushButton_23 = QPushButton(self.tab_7)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(10, 80, 181, 31))
        self.pushButton_23.setFont(font1)
        self.pushButton_23.setStyleSheet(u"background-color: rgb(19, 173, 255);\n"
"")
        self.pushButton_23.setIcon(icon5)
        self.comboBox_7 = QComboBox(self.tab_7)
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(860, 40, 151, 31))
        self.comboBox_7.setFont(font6)
        self.comboBox_7.setStyleSheet(u"background-color: rgb(246, 239, 255);")
        self.label_15 = QLabel(self.tab_7)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(770, 40, 51, 20))
        self.label_15.setFont(font1)
        self.pushButton_30 = QPushButton(self.tab_7)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(860, 490, 161, 41))
        self.pushButton_30.setFont(font1)
        self.pushButton_30.setStyleSheet(u"background-color: rgb(112, 255, 133);")
        icon10 = QIcon()
        icon10.addFile(u"../../.designer/icone/export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_30.setIcon(icon10)
        self.tabWidget.addTab(self.tab_7, "")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(50, 130, 201, 61))
        self.pushButton.setFont(font1)
        self.pushButton.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon11 = QIcon()
        icon11.addFile(u":/icone/vente.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon11)
        self.pushButton.setIconSize(QSize(28, 28))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(50, 200, 201, 61))
        self.pushButton_2.setFont(font1)
        self.pushButton_2.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon12 = QIcon()
        icon12.addFile(u":/icone/product.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon12)
        self.pushButton_2.setIconSize(QSize(28, 28))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(50, 270, 201, 61))
        self.pushButton_3.setFont(font1)
        self.pushButton_3.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon13 = QIcon()
        icon13.addFile(u":/icone/client.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon13)
        self.pushButton_3.setIconSize(QSize(28, 28))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(50, 340, 201, 61))
        self.pushButton_4.setFont(font1)
        self.pushButton_4.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon14 = QIcon()
        icon14.addFile(u":/icone/dashboard.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon14)
        self.pushButton_4.setIconSize(QSize(28, 28))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(50, 410, 201, 61))
        self.pushButton_5.setFont(font1)
        self.pushButton_5.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon15 = QIcon()
        icon15.addFile(u":/icone/report.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon15)
        self.pushButton_5.setIconSize(QSize(28, 28))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(50, 480, 201, 61))
        self.pushButton_6.setFont(font1)
        self.pushButton_6.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon16 = QIcon()
        icon16.addFile(u":/icone/param.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_6.setIcon(icon16)
        self.pushButton_6.setIconSize(QSize(28, 28))
        self.pushButton_19 = QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(50, 550, 201, 61))
        self.pushButton_19.setFont(font1)
        self.pushButton_19.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        icon17 = QIcon()
        icon17.addFile(u":/icone/historique.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_19.setIcon(icon17)
        self.pushButton_19.setIconSize(QSize(28, 28))
        self.pushButton_25 = QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(50, 60, 201, 61))
        self.pushButton_25.setFont(font1)
        self.pushButton_25.setStyleSheet(u"background-color: rgb(165, 120, 255);")
        self.pushButton_25.setIcon(icon1)
        self.pushButton_25.setIconSize(QSize(28, 28))
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.tabWidget.raise_()
        self.pushButton_19.raise_()
        self.pushButton_25.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1324, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(7)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Nom Utilisateur ", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Mot de pass ", None))
        self.lineEdit_22.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Utilisateur", None))
        self.lineEdit_23.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Mot de pass", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Mot de pass oubli\u00e9 ? ", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"R\u00e9initialiser ", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), QCoreApplication.translate("MainWindow", u"Login", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Code de produit", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"----------", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"test 2", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"New Item", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"Produit", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Ajouter", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Code Produit", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Nom Produit ", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Prix", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None));
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Vendre", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Annuler payement", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Vente", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nom de produit", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"test 1", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"test 2", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Cat\u00e9gories", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Rechercher", None))
        ___qtablewidgetitem4 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Code", None));
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Name", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Categorie", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None));
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Tous les produit", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Ajouter", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"----------", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("MainWindow", u"New Item", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Categories", None))
        self.lineEdit_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Prix", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Prix", None))
        self.lineEdit_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nom de produit", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Nom", None))
        self.lineEdit_5.setPlaceholderText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"D\u00e9tails", None))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Code", None))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Code Barre", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Ajouter Produit", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"D\u00e9tails", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.lineEdit_9.setPlaceholderText(QCoreApplication.translate("MainWindow", u"prix", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Code barre", None))
        self.lineEdit_11.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nom de produit", None))
        self.lineEdit_12.setPlaceholderText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Prix d'achat", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Code", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Recherche", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Prix de vente", None))
        self.lineEdit_24.setPlaceholderText(QCoreApplication.translate("MainWindow", u"prix", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Modifier Produit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Produit", None))
        self.lineEdit_13.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Client", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Rechercher", None))
        ___qtablewidgetitem8 = self.tableWidget_3.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"ID", None));
        ___qtablewidgetitem9 = self.tableWidget_3.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Nom", None));
        ___qtablewidgetitem10 = self.tableWidget_3.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Phone", None));
        ___qtablewidgetitem11 = self.tableWidget_3.horizontalHeaderItem(3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Email", None));
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), QCoreApplication.translate("MainWindow", u"Tous les clients", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Sauvgarder client", None))
        self.lineEdit_14.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.lineEdit_15.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nom de client", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Nom", None))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Mot de passe", None))
        self.lineEdit_18.setText("")
        self.lineEdit_18.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Mot de passe", None))
        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"Nom de client", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"Phone", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"Email", None))

        self.lineEdit_16.setPlaceholderText("")
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"Recherche", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), QCoreApplication.translate("MainWindow", u"Ajouter Client", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Clients", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Categories :", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"Ajouter Categories", None))
        self.comboBox_5.setItemText(0, QCoreApplication.translate("MainWindow", u"----------", None))
        self.comboBox_5.setItemText(1, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_5.setItemText(2, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_5.setItemText(3, QCoreApplication.translate("MainWindow", u"New Item", None))
        self.comboBox_5.setItemText(4, QCoreApplication.translate("MainWindow", u"New Item", None))

        self.lineEdit_19.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nom du categorie", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Categorie p\u00e9re", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Generate code barre :", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"Generate code barre", None))
        self.lineEdit_20.setPlaceholderText("")
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"Imprimer code barre", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Dashboard", None))
        ___qtablewidgetitem12 = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Code", None));
        ___qtablewidgetitem13 = self.tableWidget_5.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Nom produit", None));
        ___qtablewidgetitem14 = self.tableWidget_5.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Categorie", None));
        ___qtablewidgetitem15 = self.tableWidget_5.horizontalHeaderItem(3)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"Quantit\u00e9", None));
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"De", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Jusqu'a ", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"Recherche par quantit\u00e9", None))
        self.pushButton_31.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), QCoreApplication.translate("MainWindow", u"Report", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), QCoreApplication.translate("MainWindow", u"Ajouter Produit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Report", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Param\u00e9tre", None))
        ___qtablewidgetitem16 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"Utilisateur", None));
        ___qtablewidgetitem17 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"Action", None));
        ___qtablewidgetitem18 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"Table", None));
        ___qtablewidgetitem19 = self.tableWidget_4.horizontalHeaderItem(3)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        self.lineEdit_21.setPlaceholderText("")
        self.comboBox_6.setItemText(0, QCoreApplication.translate("MainWindow", u"------------", None))
        self.comboBox_6.setItemText(1, QCoreApplication.translate("MainWindow", u"Connect\u00e9", None))
        self.comboBox_6.setItemText(2, QCoreApplication.translate("MainWindow", u"Deconnect\u00e9", None))
        self.comboBox_6.setItemText(3, QCoreApplication.translate("MainWindow", u"Ajouter produit", None))
        self.comboBox_6.setItemText(4, QCoreApplication.translate("MainWindow", u"Modifier Produit", None))
        self.comboBox_6.setItemText(5, QCoreApplication.translate("MainWindow", u"Supprimer Produit", None))
        self.comboBox_6.setItemText(6, QCoreApplication.translate("MainWindow", u"Ajouter Client", None))
        self.comboBox_6.setItemText(7, QCoreApplication.translate("MainWindow", u"Modifer Client", None))
        self.comboBox_6.setItemText(8, QCoreApplication.translate("MainWindow", u"Ajouter Categories", None))
        self.comboBox_6.setItemText(9, QCoreApplication.translate("MainWindow", u"Ajouter Code Barre", None))

        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Action", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"Recherche", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Table", None))
        self.pushButton_30.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Historique", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Vente", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Produits", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Clients", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Dashboard", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Report", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Param\u00e9tre", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"Historique", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"Login", None))
    # retranslateUi

